// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package io.github.jerryofouc.simplerpc.protobuf;

public final class SimpleRPC {
  private SimpleRPC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RPCRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint64 serialNum = 1;
    /**
     * <code>required uint64 serialNum = 1;</code>
     */
    boolean hasSerialNum();
    /**
     * <code>required uint64 serialNum = 1;</code>
     */
    long getSerialNum();

    // required string methodName = 2;
    /**
     * <code>required string methodName = 2;</code>
     */
    boolean hasMethodName();
    /**
     * <code>required string methodName = 2;</code>
     */
    java.lang.String getMethodName();
    /**
     * <code>required string methodName = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    // required bytes requestParams = 3;
    /**
     * <code>required bytes requestParams = 3;</code>
     */
    boolean hasRequestParams();
    /**
     * <code>required bytes requestParams = 3;</code>
     */
    com.google.protobuf.ByteString getRequestParams();
  }
  /**
   * Protobuf type {@code tutorial.RPCRequest}
   */
  public static final class RPCRequest extends
      com.google.protobuf.GeneratedMessage
      implements RPCRequestOrBuilder {
    // Use RPCRequest.newBuilder() to construct.
    private RPCRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RPCRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RPCRequest defaultInstance;
    public static RPCRequest getDefaultInstance() {
      return defaultInstance;
    }

    public RPCRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RPCRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serialNum_ = input.readUInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              methodName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              requestParams_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SimpleRPC.internal_static_tutorial_RPCRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SimpleRPC.internal_static_tutorial_RPCRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SimpleRPC.RPCRequest.class, SimpleRPC.RPCRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<RPCRequest> PARSER =
        new com.google.protobuf.AbstractParser<RPCRequest>() {
      public RPCRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RPCRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RPCRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint64 serialNum = 1;
    public static final int SERIALNUM_FIELD_NUMBER = 1;
    private long serialNum_;
    /**
     * <code>required uint64 serialNum = 1;</code>
     */
    public boolean hasSerialNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 serialNum = 1;</code>
     */
    public long getSerialNum() {
      return serialNum_;
    }

    // required string methodName = 2;
    public static final int METHODNAME_FIELD_NUMBER = 2;
    private java.lang.Object methodName_;
    /**
     * <code>required string methodName = 2;</code>
     */
    public boolean hasMethodName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string methodName = 2;</code>
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          methodName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string methodName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bytes requestParams = 3;
    public static final int REQUESTPARAMS_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString requestParams_;
    /**
     * <code>required bytes requestParams = 3;</code>
     */
    public boolean hasRequestParams() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes requestParams = 3;</code>
     */
    public com.google.protobuf.ByteString getRequestParams() {
      return requestParams_;
    }

    private void initFields() {
      serialNum_ = 0L;
      methodName_ = "";
      requestParams_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSerialNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethodName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequestParams()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, serialNum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, requestParams_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, serialNum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, requestParams_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SimpleRPC.RPCRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SimpleRPC.RPCRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SimpleRPC.RPCRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SimpleRPC.RPCRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SimpleRPC.RPCRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SimpleRPC.RPCRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SimpleRPC.RPCRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SimpleRPC.RPCRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SimpleRPC.RPCRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SimpleRPC.RPCRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SimpleRPC.RPCRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.RPCRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements SimpleRPC.RPCRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SimpleRPC.internal_static_tutorial_RPCRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SimpleRPC.internal_static_tutorial_RPCRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SimpleRPC.RPCRequest.class, SimpleRPC.RPCRequest.Builder.class);
      }

      // Construct using io.github.jerryofouc.protobuf.SimpleRPC.RPCRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serialNum_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        methodName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        requestParams_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SimpleRPC.internal_static_tutorial_RPCRequest_descriptor;
      }

      public SimpleRPC.RPCRequest getDefaultInstanceForType() {
        return SimpleRPC.RPCRequest.getDefaultInstance();
      }

      public SimpleRPC.RPCRequest build() {
        SimpleRPC.RPCRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SimpleRPC.RPCRequest buildPartial() {
        SimpleRPC.RPCRequest result = new SimpleRPC.RPCRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serialNum_ = serialNum_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.methodName_ = methodName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.requestParams_ = requestParams_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SimpleRPC.RPCRequest) {
          return mergeFrom((SimpleRPC.RPCRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SimpleRPC.RPCRequest other) {
        if (other == SimpleRPC.RPCRequest.getDefaultInstance()) return this;
        if (other.hasSerialNum()) {
          setSerialNum(other.getSerialNum());
        }
        if (other.hasMethodName()) {
          bitField0_ |= 0x00000002;
          methodName_ = other.methodName_;
          onChanged();
        }
        if (other.hasRequestParams()) {
          setRequestParams(other.getRequestParams());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSerialNum()) {
          
          return false;
        }
        if (!hasMethodName()) {
          
          return false;
        }
        if (!hasRequestParams()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SimpleRPC.RPCRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SimpleRPC.RPCRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint64 serialNum = 1;
      private long serialNum_ ;
      /**
       * <code>required uint64 serialNum = 1;</code>
       */
      public boolean hasSerialNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 serialNum = 1;</code>
       */
      public long getSerialNum() {
        return serialNum_;
      }
      /**
       * <code>required uint64 serialNum = 1;</code>
       */
      public Builder setSerialNum(long value) {
        bitField0_ |= 0x00000001;
        serialNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 serialNum = 1;</code>
       */
      public Builder clearSerialNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serialNum_ = 0L;
        onChanged();
        return this;
      }

      // required string methodName = 2;
      private java.lang.Object methodName_ = "";
      /**
       * <code>required string methodName = 2;</code>
       */
      public boolean hasMethodName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string methodName = 2;</code>
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string methodName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string methodName = 2;</code>
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string methodName = 2;</code>
       */
      public Builder clearMethodName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>required string methodName = 2;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
        return this;
      }

      // required bytes requestParams = 3;
      private com.google.protobuf.ByteString requestParams_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes requestParams = 3;</code>
       */
      public boolean hasRequestParams() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes requestParams = 3;</code>
       */
      public com.google.protobuf.ByteString getRequestParams() {
        return requestParams_;
      }
      /**
       * <code>required bytes requestParams = 3;</code>
       */
      public Builder setRequestParams(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        requestParams_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes requestParams = 3;</code>
       */
      public Builder clearRequestParams() {
        bitField0_ = (bitField0_ & ~0x00000004);
        requestParams_ = getDefaultInstance().getRequestParams();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.RPCRequest)
    }

    static {
      defaultInstance = new RPCRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.RPCRequest)
  }

  public interface RPCResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint64 serialNum = 1;
    /**
     * <code>required uint64 serialNum = 1;</code>
     */
    boolean hasSerialNum();
    /**
     * <code>required uint64 serialNum = 1;</code>
     */
    long getSerialNum();

    // required bytes responseData = 2;
    /**
     * <code>required bytes responseData = 2;</code>
     */
    boolean hasResponseData();
    /**
     * <code>required bytes responseData = 2;</code>
     */
    com.google.protobuf.ByteString getResponseData();
  }
  /**
   * Protobuf type {@code tutorial.RPCResponse}
   */
  public static final class RPCResponse extends
      com.google.protobuf.GeneratedMessage
      implements RPCResponseOrBuilder {
    // Use RPCResponse.newBuilder() to construct.
    private RPCResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RPCResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RPCResponse defaultInstance;
    public static RPCResponse getDefaultInstance() {
      return defaultInstance;
    }

    public RPCResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RPCResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serialNum_ = input.readUInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              responseData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SimpleRPC.internal_static_tutorial_RPCResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SimpleRPC.internal_static_tutorial_RPCResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SimpleRPC.RPCResponse.class, SimpleRPC.RPCResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<RPCResponse> PARSER =
        new com.google.protobuf.AbstractParser<RPCResponse>() {
      public RPCResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RPCResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RPCResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint64 serialNum = 1;
    public static final int SERIALNUM_FIELD_NUMBER = 1;
    private long serialNum_;
    /**
     * <code>required uint64 serialNum = 1;</code>
     */
    public boolean hasSerialNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 serialNum = 1;</code>
     */
    public long getSerialNum() {
      return serialNum_;
    }

    // required bytes responseData = 2;
    public static final int RESPONSEDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString responseData_;
    /**
     * <code>required bytes responseData = 2;</code>
     */
    public boolean hasResponseData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes responseData = 2;</code>
     */
    public com.google.protobuf.ByteString getResponseData() {
      return responseData_;
    }

    private void initFields() {
      serialNum_ = 0L;
      responseData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSerialNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResponseData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, serialNum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, responseData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, serialNum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, responseData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SimpleRPC.RPCResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SimpleRPC.RPCResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SimpleRPC.RPCResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SimpleRPC.RPCResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SimpleRPC.RPCResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SimpleRPC.RPCResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SimpleRPC.RPCResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SimpleRPC.RPCResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SimpleRPC.RPCResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SimpleRPC.RPCResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SimpleRPC.RPCResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.RPCResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements SimpleRPC.RPCResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SimpleRPC.internal_static_tutorial_RPCResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SimpleRPC.internal_static_tutorial_RPCResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SimpleRPC.RPCResponse.class, SimpleRPC.RPCResponse.Builder.class);
      }

      // Construct using io.github.jerryofouc.protobuf.SimpleRPC.RPCResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serialNum_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        responseData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SimpleRPC.internal_static_tutorial_RPCResponse_descriptor;
      }

      public SimpleRPC.RPCResponse getDefaultInstanceForType() {
        return SimpleRPC.RPCResponse.getDefaultInstance();
      }

      public SimpleRPC.RPCResponse build() {
        SimpleRPC.RPCResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SimpleRPC.RPCResponse buildPartial() {
        SimpleRPC.RPCResponse result = new SimpleRPC.RPCResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serialNum_ = serialNum_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.responseData_ = responseData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SimpleRPC.RPCResponse) {
          return mergeFrom((SimpleRPC.RPCResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SimpleRPC.RPCResponse other) {
        if (other == SimpleRPC.RPCResponse.getDefaultInstance()) return this;
        if (other.hasSerialNum()) {
          setSerialNum(other.getSerialNum());
        }
        if (other.hasResponseData()) {
          setResponseData(other.getResponseData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSerialNum()) {
          
          return false;
        }
        if (!hasResponseData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SimpleRPC.RPCResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SimpleRPC.RPCResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint64 serialNum = 1;
      private long serialNum_ ;
      /**
       * <code>required uint64 serialNum = 1;</code>
       */
      public boolean hasSerialNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 serialNum = 1;</code>
       */
      public long getSerialNum() {
        return serialNum_;
      }
      /**
       * <code>required uint64 serialNum = 1;</code>
       */
      public Builder setSerialNum(long value) {
        bitField0_ |= 0x00000001;
        serialNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 serialNum = 1;</code>
       */
      public Builder clearSerialNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serialNum_ = 0L;
        onChanged();
        return this;
      }

      // required bytes responseData = 2;
      private com.google.protobuf.ByteString responseData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes responseData = 2;</code>
       */
      public boolean hasResponseData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes responseData = 2;</code>
       */
      public com.google.protobuf.ByteString getResponseData() {
        return responseData_;
      }
      /**
       * <code>required bytes responseData = 2;</code>
       */
      public Builder setResponseData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        responseData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes responseData = 2;</code>
       */
      public Builder clearResponseData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        responseData_ = getDefaultInstance().getResponseData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.RPCResponse)
    }

    static {
      defaultInstance = new RPCResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.RPCResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_RPCRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_RPCRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_RPCResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_RPCResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\trpc.proto\022\010tutorial\"J\n\nRPCRequest\022\021\n\ts" +
      "erialNum\030\001 \002(\004\022\022\n\nmethodName\030\002 \002(\t\022\025\n\rre" +
      "questParams\030\003 \002(\014\"6\n\013RPCResponse\022\021\n\tseri" +
      "alNum\030\001 \002(\004\022\024\n\014responseData\030\002 \002(\014B*\n\035io." +
      "github.jerryofouc.protobufB\tSimpleRPC"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_RPCRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_RPCRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_RPCRequest_descriptor,
              new java.lang.String[] { "SerialNum", "MethodName", "RequestParams", });
          internal_static_tutorial_RPCResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_tutorial_RPCResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_RPCResponse_descriptor,
              new java.lang.String[] { "SerialNum", "ResponseData", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
